name: msbuild-repro-test

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  msbuild_16_8:
    name: windows-test-16-8
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: show msbuild version
        run: msbuild -version
      - uses: nuget/setup-nuget@v1
      - name: nuget restore
        run: nuget restore mixed.sln
      - name: build using msbuild
        run: msbuild mixed.sln -graphBuild:True
