name: msbuild-repro-test

on:
  push:
    branches:
      - "master"

jobs:
  msbuild_16_8:
    name: windows-test-16-8
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: 16.8
      - name: show msbuild version
        run: msbuild -version
      - uses: nuget/setup-nuget@v1
        run: nuget restore mixed.sln
      - name: build using msbuild
        run: msbuild mixed.sln

  msbuild_16_7:
    name: windows-test-16-7
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: 16.7
      - name: show msbuild version
        run: msbuild -version
      - uses: nuget/setup-nuget@v1
        run: nuget restore mixed.sln
      - name: build using msbuild
        run: msbuild mixed.sln
