name: msbuild-repro-test

on:
  push:
    branches:
      - "master"

jobs:
  msbuild_16_8:
    name: windows-test
    runs-on: windows-latest
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: 16.8
      - name: echo MSBuild
        run: msbuild -version
